#!/usr/bin/python2
# -*- coding: UTF-8 -*-

import sys
import getopt
from app import main as appMain


def main():
    argv = sys.argv
    if len(argv) != 3:
        print "Invalid arguments"
        return 1;
    print "Learning set: %s" % argv[1]
    print "Testing set: %s" % argv[2]
    appMain(learning_set_dir = argv[1], testing_set_dir = argv[2]);

if __name__ == "__main__":
    main()
